# Generated by Django 3.2.7 on 2021-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='is_referenced',
            field=models.BooleanField(default=False),
        ),
    ]
