# Generated by Django 3.2.7 on 2021-10-02 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('slots', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('account', models.CharField(max_length=250)),
                ('is_bank', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='adventure.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Inclusives',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusives', to='adventure.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_id', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adventure.adventure')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='payment_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adventure', to='adventure.paymentchannel'),
        ),
    ]
