# Generated by Django 3.2.7 on 2021-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='payment_channel',
        ),
        migrations.AddField(
            model_name='adventure',
            name='payment_channel',
            field=models.ManyToManyField(related_name='adventure', to='adventure.PaymentChannel'),
        ),
    ]
