# Generated by Django 3.2.7 on 2021-10-03 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20211003_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='reference_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
