# Generated by Django 3.2.7 on 2021-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_adventure_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='child',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
