# Generated by Django 3.2.7 on 2021-10-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20211003_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='adventure_status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('COMPLETE', 'COMPLETE')], default='ONGOING', max_length=500),
        ),
        migrations.AddField(
            model_name='adventure',
            name='created_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
