# Generated by Django 3.2.7 on 2021-10-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_auto_20211006_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentchannel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
